//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Libros
    {
        public long ID_Libro { get; set; }
        public Nullable<long> ID_Reserva { get; set; }
        public long ID_Tarifa { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string Categoria { get; set; }
        public int Ejemplares { get; set; }
        public string Imagen { get; set; }
        public string Estado { get; set; }
        public int EstadoRegistro { get; set; }
    
        public virtual Reservas Reservas { get; set; }
        public virtual Tarifas Tarifas { get; set; }
    }
}
