//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookRentalApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservas()
        {
            this.Libros = new HashSet<Libros>();
        }
    
        public long ID_Reserva { get; set; }
        public long ID_Usuario { get; set; }
        public long ID_Libro { get; set; }
        public decimal ValorReserva { get; set; }
        public System.DateTime FechaReserva { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public string Estado { get; set; }
        public int EstadoRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Libros> Libros { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
